version: '2.1'

services:
  mlinar-api:
    image: mlinar-api
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 9229:9229
    ## set your startup file here
    command: npm run debug