version: '2.1'

services:
  mlinar-api:
    image: mlinar-api-dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      DB_URL: ${DB_URL}
      DB_USER:  ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
    ports:
      - 80:80
      - 9229:9229
    ## set your startup file here
    volumes: 
      - .:/usr/src/app