FROM node:carbon-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent -g nodemon

RUN npm install --production --silent && mv node_modules ../
EXPOSE 80 9229
CMD nodemon --exec npm run inspect